// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwijrevsaiyhawqvirap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWpyZXZzYWl5aGF3cXZpcmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDg5MjQsImV4cCI6MjA2MTg4NDkyNH0.mlCSBbeY5hMNzESOpphFE5aEWmS04DS9gWBSNca1Ujo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);